apiVersion: v1
kind: Service
metadata:
  name: flask-expense-tracker-service
spec:
  selector:
    app: expensetracker
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
